<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Backend Auth Items' => '用户和权限列表',
    'Create {modelClass}' => '添加 {modelClass}',
    'Backend Auth Item' => '用户和权限',
    'Order Manage' => '订单管理',
    'Create Order' => '添加订单',
    'Name' => '名称',
    'Type' => '类型',
    'Description' => '简介',
    'Rule Name' => '规则名称',
    'Data' => '数据',
    'Created At' => '创建日期',
    'Updated At' => '更新日期',
    'Update {modelClass}: ' => '更新 {modelClass}: ',
    'Update' => '更新',
];
